[workspace]
resolver = "3"
members = ["fennel-graphics", "fennel-runtime", "fennel-physics", "fennel-plugins", "fennel-gpu", "fennel-resources", "fennel-audio", "fennel-2d", "fennel-registry", "examples/game"]
