[[assets]]
name = "example"
path = "example.png"
type = "Image"

[[assets]]
name = "Terminus"
path = "terminus.ttf"
type = "Font"

[[assets]]
name = "tile_bg_empty"
path = "Sprite-0001.png"
type = "Image"