[package]
name = "fennel-physics"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.34.1"
plotters = "0.3.7"
specs = { version = "0.20.0", optional = true }

[features]
specs = ["dep:specs"]